All working except for sonarr

diff --git a/k8s/servarr/charts/servarr/values.yaml b/k8s/servarr/charts/servarr/values.yaml
--- a/k8s/servarr/charts/servarr/values.yaml
+++ b/k8s/servarr/charts/servarr/values.yaml
@@ -267,7 +267,7 @@ sonarr:
   image:
     repository: lscr.io/linuxserver/sonarr
     pullPolicy: IfNotPresent
-    tag: "4.0.10"
+    tag: "4.0.16"
 
   imagePullSecrets: []
 
@@ -300,7 +300,7 @@ sonarr:
   # -- Init Containers
   initContainers: &extra-initcontainers
     - name: gluetun
-      image: qmcgaw/gluetun:latest
+      image: qmcgaw/gluetun:pr-2970
       restartPolicy: Always
       securityContext:
         capabilities:
@@ -319,21 +319,30 @@ sonarr:
               key: privateKey
         - name: TZ
           value: Europe/Paris
-        - name: BLOCK_OUTSIDE_VPN
-          value: "true"
         - name: FIREWALL
           value: "true"
         - name: FIREWALL_OUTBOUND_SUBNETS
           value: 10.0.0.0/8
-        - name: DNS_PLAINTEXT_ADDRESS
-          value: "10.43.0.10"
         - name: EXTRA_SUBNETS_ALLOWED
-          value: 10.42.0.0/16, 10.43.0.10
+          value: "10.42.0.0/16,10.43.0.0/16"
         - name: FIREWALL_INPUT_PORTS
-          value: 9696,8989
+          value: "8989,7878,9696,8080,8096,8686,6767,8191"
       volumeMounts:
         - name: tun
           mountPath: /dev/net/tun
+    - name: ping
+      image: busybox
+      command: 
+        - sh
+        - -c
+        - |
+          sleep 30
+          while ! ping -c 1 8.8.8.8; do
+            echo "Ping failed, retrying in 5"
+            sleep 5
+          done
+          echo "ping succesfull, exiting"
+
 
   service:
     type: ClusterIP
@@ -342,7 +351,7 @@ sonarr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -380,7 +389,7 @@ sonarr:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
     UMASK: "002"
 
   persistence:
@@ -484,9 +493,6 @@ qbittorrent:
     # runAsUser: 1000
 
   initContainers: *extra-initcontainers
-    # - name: init-container
-    #   image: busybox
-    #   command: ['sh', '-c', 'echo "this is an init container"']
 
   service:
     web:
@@ -499,13 +505,13 @@ qbittorrent:
       nodePort: ""
 
   ingress:
-    enabled: false
-    className: ""
+    enabled: true
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
     hosts:
-      - host: chart-example.local
+      - host: qbittorrent.media.local
         paths:
           - path: /
             pathType: ImplementationSpecific
@@ -538,7 +544,7 @@ qbittorrent:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
 
   persistence:
     enabled: true
@@ -549,6 +555,17 @@ qbittorrent:
     size: 800Mi
     additionalMounts: *additional-mounts
     additionalVolumes: *additional-volumes
+
+  additionalQbittorrentMounts:
+    - name: qbittorrent-config
+      mountPath: /config/qBittorrent/qBittorrent.conf
+      subPath: qBittorrent.conf
+      readOnly: true
+
+  additionalQbittorrentVolumes:
+    - name: qbittorrent-config
+      configMap:
+        name: qbittorrent-config
 
 ## @section Prowlarr parameters
 
@@ -640,7 +657,7 @@ prowlarr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -678,7 +695,7 @@ prowlarr:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
     UMASK: "002"
 
   persistence:
@@ -784,13 +801,13 @@ flaresolverr:
     nodePort: ""
 
   ingress:
-    enabled: false
-    className: ""
+    enabled: true
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
     hosts:
-      - host: chart-example.local
+      - host: flaresolverr.media.local
         paths:
           - path: /
             pathType: ImplementationSpecific
@@ -909,7 +926,7 @@ jellyseerr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -1041,7 +1058,7 @@ bazarr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -1079,7 +1096,7 @@ bazarr:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
 
   persistence:
     enabled: true
@@ -1180,7 +1197,7 @@ radarr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -1218,7 +1235,7 @@ radarr:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
     UMASK: "002"
 
   persistence:
@@ -1323,7 +1340,7 @@ lidarr:
 
   ingress:
     enabled: false
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -1361,7 +1378,7 @@ lidarr:
   env:
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
     UMASK: "002"
 
   persistence:
@@ -1468,7 +1485,7 @@ cleanuparr:
 
   ingress:
     enabled: true
-    className: ""
+    className: "traefik"
     annotations: {}
       # kubernetes.io/ingress.class: nginx
       # kubernetes.io/tls-acme: "true"
@@ -1508,7 +1525,7 @@ cleanuparr:
     PORT: "11011"
     PUID: "1000"
     PGID: "1000"
-    TZ: "Europe/London"
+    TZ: "Europe/Paris"
     UMASK: "002"
 
   persistence:
